version: '3.8'

services:
  # PostgreSQL
  pms_v3-mysql:
    image: mysql:8.0
    container_name: pms_v3-mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - django-pms-network

  # Redis
  pms_v3-redis:
    image: redis:7-alpine
    container_name: pms_v3-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - django-pms-network

  # Django 웹 애플리케이션 컨테이너
  pms_v3-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DJANGO_ENV: ${DJANGO_ENV:-local}
    container_name: pms_v3-web
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      pms_v3-mysql:
        condition: service_healthy
      pms_v3-redis:
        condition: service_healthy
    networks:
      - django-pms-network

  pms_v3-celery-worker:
    build: .
    container_name: pms_v3-celery-worker
    command: celery -A pms_v3 worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - django-pms-network

  pms_v3-celery-beat:
    build: .
    container_name: pms_v3-celery-beat
    command: celery -A pms_v3 beat -l info
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - django-pms-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  django-pms-network: