apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms-web-celery-worker
  namespace: pms-web
  labels:
    app: pms-web-celery-worker
spec:
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pms-web-celery-worker
  template:
    metadata:
      labels:
        app: pms-web-celery-worker
    spec:
      containers:
      - name: worker
        image: dsct/daesan-pms:latest
        imagePullPolicy: Always
        command: ["celery", "-A", "pms_v3", "worker", "-l", "info"]

        envFrom:
          - secretRef:
              name: pms-web-secrets

        env:
          - name: DJANGO_ENV
            value: "prod"

        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms-web-celery-beat
  namespace: pms-web
  labels:
    app: pms-web-celery-beat
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: pms-web-celery-beat
  template:
    metadata:
      labels:
        app: pms-web-celery-beat
    spec:
      containers:
      - name: beat
        image: dsct/daesan-pms:latest
        imagePullPolicy: Always
        command: ["celery", "-A", "pms_v3", "beat", "-l", "info"]

        envFrom:
          - secretRef:
              name: pms-web-secrets

        env:
          - name: DJANGO_ENV
            value: "prod"

        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"